---
- hosts: localhost
  become: true
  gather_facts: no
  connection: local

  tasks:
  - set_fact: BUILD_ID="{{ lookup('env','BUILD_ID') }}"
  - name: Build New Docker Image
    docker_image:
      path: ./tomcat
      name: mukeshjadav7696/msj-jpdk
      tag: pipeline-{{build_id}}
    register: docker_build
  - debug:
      msg: "Docker Image Build Done: mukeshjadav7696/msj-jpdkt:pipeline-{{build_id}}"
